/* COUNT */
SELECT COUNT(*) FROM EMPLOYEES;

SELECT COUNT(MANAGER_ID) FROM EMPLOYEES;

/* AVG */
SELECT AVG(SALARY) FROM EMPLOYEES;

SELECT DEPARTMENT_ID, TO_CHAR(AVG(SALARY), '99999') FROM EMPLOYEES GROUP BY DEPARTMENT_ID;
SELECT DEPARTMENT_ID, TO_CHAR(AVG(SALARY), '99999'),TO_CHAR(SUM(SALARY), '99999'),
                      TO_CHAR(MAX(SALARY), '99999'), TO_CHAR(MIN(SALARY), '99999')
                      FROM EMPLOYEES
GROUP BY DEPARTMENT_ID; --집계함수들
SELECT DEPARTMENT_ID, TO_CHAR(AVG(SALARY), '99,999') AS AVG_SALARY,
                      TO_CHAR(SUM(SALARY), '999,999,999'),TO_CHAR(MAX(SALARY), '99,999'), TO_CHAR(MIN(SALARY), '99,999')
                      FROM EMPLOYEES
GROUP BY DEPARTMENT_ID ORDER BY AVG_SALARY; --별칭 지정도 가능

/* 사장님을 뺀 사원들의 부서별 평균 연봉이 5000 이상인 부서와 평균연봉을 높은 순으로 출력*/
SELECT DEPARTMENT_ID, AVG(SALARY) FROM EMPLOYEES WHERE DEPARTMENT_ID IS NOT NULL GROUP BY DEPARTMENT_ID HAVING AVG(SALARY)>5000
                                                 ORDER BY AVG(SALARY) DESC;