DESC EMPLOYEES;

SELECT * FROM JOBS;

SELECT * FROM DEPARTMENTS;

SELECT * FROM LOCATIONS;

SELECT * FROM JOB_HISTORY;

SELECT FIRST_NAME, LAST_NAME FROM EMPLOYEES WHERE EMPLOYEE_ID = 101;

SELECT * FROM JOB_HISTORY WHERE EMPLOYEE_ID = 101;